apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: service-registry
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    config:
      inter.broker.protocol.version: '2.8'
      log.message.format.version: '2.8'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - authentication:
          checkIssuer: true
          jwksEndpointUri: >-
            https://keycloak-service-registry.apps-crc.testing/auth/realms/registry/protocol/openid-connect/certs
          userNameClaim: preferred_username
          checkAccessTokenType: true
          accessTokenIsJwt: true
          enableOauthBearer: true
          validIssuerUri: >-
            https://keycloak-service-registry.apps-crc.testing/auth/realms/registry
          tlsTrustedCertificates:
            - certificate: keycloak.crt
              secretName: ca-keycloak
          type: oauth
        name: external
        port: 9094
        tls: true
        type: route
    logging:
      loggers:
        log4j.logger.io.strimzi: DEBUG
      type: inline
    replicas: 1
    storage:
      type: ephemeral
    version: 2.8.0
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral

